//
// Created by 梦想家xixi on 2021/12/22.
//

#ifndef MUTECT2CPP_MASTER_ABSTRACTSAMHEADERRECORD_H
#define MUTECT2CPP_MASTER_ABSTRACTSAMHEADERRECORD_H


class AbstractSAMHeaderRecord {

};


#endif //MUTECT2CPP_MASTER_ABSTRACTSAMHEADERRECORD_H
